### ISSUE TITLE
For the oracle prod servers the memory utilization of individual processes is coming over 100%

### ISSUE THREAD

**Issue by PradeepP29** [sschwartzman/newrelic-unix-plugin#43]
Hi Seth,
I think Keegan Peet had a discussion with you on this issue.The memory utlization of processes is reflecting over 100% for few servers.He had told you will respond to the mail which we are in loop.Till now i didnt got any update.So raising the issue in the portal.

**Comment by sschwartzman** [comment]
Hi Pradeep,

I told this to Keagan at the time, but there is no easy fix for this issue - it is due to how these servers are reporting memory usage from Oracle, which uses shared memory spaces (when you run "ps" command, you see the same memory pools repeatedly). The only thing I can offer is for us to ignore Oracle processes for the sake of memory usage on that server, but I'd think that wouldn't be helpful because of the gap in visibility that would come with it.

Please let me know how you would like to proceed.

Thanks,
Seth

**Comment by PradeepP29** [comment]
Hi Seth,
If in the server it is reflecting like that for the server,we understand that we cant do anything.Ok we will inform the application team that in the server also it is reporting like the same.Thanks for your response and help.
