### ISSUE TITLE
High CPU utilization with 0 sys, 0 user, 0 wait

### ISSUE THREAD

**Issue by 1337newbee** [sschwartzman/newrelic-unix-plugin#49]
Hi 

I had an alert from CPU utilization, showing me the CPU usage is above 90%. 
![image](https://user-images.githubusercontent.com/5840960/34385371-4bea334a-eaf0-11e7-88c1-e80d1394bcce.png)

This [code](https://github.com/sschwartzman/newrelic-unix-plugin/blob/master/src/com/chocolatefactory/newrelic/plugins/utils/CommandMetricUtils.java#L41) showed the CPU utilization = CPU - idle, which explains why we got 100% CPU utilization, as idle was 0. But at the same time, CPU user, CPU system is 0, so basically we didn't have any load on the system. We do see CPU stolen increased to 40%-50%  during that period of time. My question is should we calculate CPU utilization by simply deducting CPU_idle or we should do the other way around? e.g. CPU utilization = CPU_wait + CPU_user+ CPU_system + CPU_steal

**Comment by sschwartzman** [comment]
I think it's coded that way in this version to deal with some systems lacking metrics to accurately calculate utilization, so I went with the lowest-common-denominator of 100-idle. You could change the code to work specific to your OS.

**Comment by Reiner030** [comment]
I have this problem also but only with AWS t2 instances.

From data monitored it looks - like above also - that the "stolen CPU time" is the problem which causes somehow a miscalculation so that in the plugin list overview the CPU usage is shown as 100% which automatically creates alerts with in this plugin default setup/activated alarming by 80% warn / 90% crit values.

![snapshot of plugin list](https://goo.gl/MjWNPo)
![snapshot of plugin overview](https://goo.gl/HZV7Q7)

**Comment by sschwartzman** [comment]
Please try the new plugin (which reports to NR Insights) and report any issues there: https://github.com/newrelic-experts/unix-infra-monitor
